// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbYvLgb_JZC0TkkOs54jTU_i9DISCTiQ',
    appId: '1:607459927963:web:9c45a3957ea5b7bd1fe33e',
    messagingSenderId: '607459927963',
    projectId: 'royal-event-app',
    authDomain: 'royal-event-app.firebaseapp.com',
    storageBucket: 'royal-event-app.firebasestorage.app',
    measurementId: 'G-XE3V1D2YRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVX2aGUdI1POwAQT40qwVAlUVQh-tKCCc',
    appId: '1:607459927963:android:e38dad5eb24e62621fe33e',
    messagingSenderId: '607459927963',
    projectId: 'royal-event-app',
    storageBucket: 'royal-event-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJAr-sH91Bb519koLYTqB9VWrDUcgcYw',
    appId: '1:607459927963:ios:bafbe33d9ccb4b821fe33e',
    messagingSenderId: '607459927963',
    projectId: 'royal-event-app',
    storageBucket: 'royal-event-app.firebasestorage.app',
    iosBundleId: 'com.example.eventsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJAr-sH91Bb519koLYTqB9VWrDUcgcYw',
    appId: '1:607459927963:ios:bafbe33d9ccb4b821fe33e',
    messagingSenderId: '607459927963',
    projectId: 'royal-event-app',
    storageBucket: 'royal-event-app.firebasestorage.app',
    iosBundleId: 'com.example.eventsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHbYvLgb_JZC0TkkOs54jTU_i9DISCTiQ',
    appId: '1:607459927963:web:9d636bf9510614911fe33e',
    messagingSenderId: '607459927963',
    projectId: 'royal-event-app',
    authDomain: 'royal-event-app.firebaseapp.com',
    storageBucket: 'royal-event-app.firebasestorage.app',
    measurementId: 'G-DX6HP3SGPF',
  );
}
